My Project: Matrix< T > Class Template Reference
Matrix< T > Class Template Reference
Template class representing a mathematical matrix.
#include <Matrix.hpp>
Public Member Functions
Matrix ()
Default constructor creates an empty matrix (0x0).
Matrix (int rows, int cols, const T &initVal=T())
Constructs a matrix with given dimensions, initializing all elements with initVal.
Matrix (const Matrix &other)=default
Copy constructor (defaulted)
Matrix (Matrix &&other) noexcept=default
Move constructor (defaulted)
Matrix & operator= (const Matrix &other)=default
Copy assignment operator (defaulted)
Matrix & operator= (Matrix &&other) noexcept=default
Move assignment operator (defaulted)
~Matrix ()=default
Destructor (defaulted)
T & operator() (int row, int col)
Access element at specified position (non-const).
const T & operator() (int row, int col) const
Access element at specified position (const).
Matrix< T > operator+ (const Matrix< T > &other) const
Matrix addition.
Matrix< T > operator- (const Matrix< T > &other) const
Matrix subtraction.
Matrix< T > operator* (const Matrix< T > &other) const
Matrix multiplication.
Matrix< T > operator* (const T &scalar) const
Scalar multiplication.
Matrix< T > transpose () const
Transpose of the matrix.
T & determinant () const
Calculate the determinant of the matrix.
void print (std::ostream &os=std::cout) const
Print the matrix to the specified output stream.
int getRows () const
Get the number of rows.
int getCols () const
Get the number of columns.
Static Public Member Functions
static Matrix< T > identityMatrix (int size)
Generate an identity matrix of given size.
static Matrix< T > randomMatrix (int rows, int cols, T minValue, T maxValue)
Generate a random matrix with values between minValue and maxValue.
static Matrix< T > randomGorat (int rows, int cols, T minValue, T maxValue)
Generate a random matrix using Gorat initialization.
static Matrix< T > randomHe (int rows, int cols, T minValue, T maxValue)
Generate a random matrix using He initialization.
Detailed Description
template<typename T>
class Matrix< T >
Template class representing a mathematical matrix.
Provides basic matrix operations such as addition, subtraction, multiplication (both scalar and matrix), transpose, determinant calculation, and methods for generating special matrices (identity, random).
Template Parameters
T The type of the elements stored in the matrix.
Definition at line 15 of file Matrix.hpp.
Constructor & Destructor Documentation
Matrix() [1/4]
template<typename T> Matrix< T >::Matrix () inline
Default constructor creates an empty matrix (0x0).
Definition at line 26 of file Matrix.hpp.
: rows(0), cols(0) {}
Referenced by identityMatrix(), Matrix(), Matrix(), operator*(), operator*(), operator+(), operator-(), operator=(), operator=(), randomGorat(), randomHe(), randomMatrix(), and transpose().
Matrix() [2/4]
template<typename T> Matrix< T >::Matrix (int rows, int cols, const T & initVal = T())
Constructs a matrix with given dimensions, initializing all elements with initVal.
Parameters
rows Number of rows
cols Number of columns
initVal Initial value for all elements (default constructed if not provided)
Matrix() [3/4]
template<typename T> Matrix< T >::Matrix (const Matrix< T > & other) default
Copy constructor (defaulted)
References Matrix().
Matrix() [4/4]
template<typename T> Matrix< T >::Matrix (Matrix< T > && other) default noexcept
Move constructor (defaulted)
References Matrix().
~Matrix()
template<typename T> Matrix< T >::~Matrix () default
Destructor (defaulted)
Member Function Documentation
determinant()
template<typename T> T & Matrix< T >::determinant () const
Calculate the determinant of the matrix.
Returns
The determinant value
Exceptions
std::logic_error if the matrix is not square
getCols()
template<typename T> int Matrix< T >::getCols () const inline
Get the number of columns.
Returns
Number of columns in the matrix
Definition at line 185 of file Matrix.hpp.
{ return cols; }
getRows()
template<typename T> int Matrix< T >::getRows () const inline
Get the number of rows.
Returns
Number of rows in the matrix
Definition at line 178 of file Matrix.hpp.
{ return rows; }
identityMatrix()
template<typename T> static Matrix< T > Matrix< T >::identityMatrix (int size) static
Generate an identity matrix of given size.
Parameters
size Size of the identity matrix (rows = cols = size)
Returns
Identity matrix of given size
References Matrix().
operator()() [1/2]
template<typename T> T & Matrix< T >::operator() (int row, int col)
Access element at specified position (non-const).
Parameters
row Row index (0-based)
col Column index (0-based)
Returns
Reference to the element at (row, col)
Exceptions
std::out_of_range if indices are out of bounds
operator()() [2/2]
template<typename T> const T & Matrix< T >::operator() (int row, int col) const
Access element at specified position (const).
Parameters
row Row index (0-based)
col Column index (0-based)
Returns
Const reference to the element at (row, col)
Exceptions
std::out_of_range if indices are out of bounds
operator*() [1/2]
template<typename T> Matrix< T > Matrix< T >::operator* (const Matrix< T > & other) const
Matrix multiplication.
Parameters
other The matrix to multiply by
Returns
A new matrix representing the product of *this and other
Exceptions
std::invalid_argument if inner dimensions do not match
References Matrix().
operator*() [2/2]
template<typename T> Matrix< T > Matrix< T >::operator* (const T & scalar) const
Scalar multiplication.
Parameters
scalar The scalar value to multiply by
Returns
A new matrix where each element is multiplied by scalar
References Matrix().
operator+()
template<typename T> Matrix< T > Matrix< T >::operator+ (const Matrix< T > & other) const
Matrix addition.
Parameters
other The matrix to add
Returns
A new matrix that is the sum of *this and other
Exceptions
std::invalid_argument if dimensions do not match
References Matrix().
operator-()
template<typename T> Matrix< T > Matrix< T >::operator- (const Matrix< T > & other) const
Matrix subtraction.
Parameters
other The matrix to subtract
Returns
A new matrix that is the difference of *this and other
Exceptions
std::invalid_argument if dimensions do not match
References Matrix().
operator=() [1/2]
template<typename T> Matrix & Matrix< T >::operator= (const Matrix< T > & other) default
Copy assignment operator (defaulted)
References Matrix().
operator=() [2/2]
template<typename T> Matrix & Matrix< T >::operator= (Matrix< T > && other) default noexcept
Move assignment operator (defaulted)
References Matrix().
print()
template<typename T> void Matrix< T >::print (std::ostream & os = std::cout) const
Print the matrix to the specified output stream.
Parameters
os Output stream (default: std::cout)
randomGorat()
template<typename T> static Matrix< T > Matrix< T >::randomGorat (int rows, int cols, T minValue, T maxValue) static
Generate a random matrix using Gorat initialization.
Parameters
rows Number of rows
cols Number of columns
minValue Minimum random value
maxValue Maximum random value
Returns
A matrix initialized with the Gorat method
References Matrix().
randomHe()
template<typename T> static Matrix< T > Matrix< T >::randomHe (int rows, int cols, T minValue, T maxValue) static
Generate a random matrix using He initialization.
Parameters
rows Number of rows
cols Number of columns
minValue Minimum random value
maxValue Maximum random value
Returns
A matrix initialized with the He method
References Matrix().
randomMatrix()
template<typename T> static Matrix< T > Matrix< T >::randomMatrix (int rows, int cols, T minValue, T maxValue) static
Generate a random matrix with values between minValue and maxValue.
Parameters
rows Number of rows
cols Number of columns
minValue Minimum random value
maxValue Maximum random value
Returns
A matrix filled with random values
References Matrix().
transpose()
template<typename T> Matrix< T > Matrix< T >::transpose () const
Transpose of the matrix.
Returns
A new matrix that is the transpose of *this
References Matrix().
The documentation for this class was generated from the following file:
/home/harryfoster/personalgit/learn-ai/include/Matrix.hpp